---
extends:
- airbnb-base
env:
  browser: true
  node: true
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    experimentalObjectRestSpread: true
rules:
  no-console: 'off'
  comma-dangle: 'off'
globals:
  NProgress: true
